name : demo5
on : [push]
env  :
   SECRET_ID : ${{secrets.AMAZON_ID}}

jobs : 
   secretcheck :
      runs-on : windows-latest
      steps : 
      - name : secret check
        uses : actions/checkout@v2
        with : 
             AID : ${{secrets.AMAZON_ID}}
          
      - run : echo "cannot be shown bcs it secret "
