name : demo6
on : [push]

jobs : 
   artifactsupload :
    runs-on : windows-latest
    steps : 
      - name : upload artifacts
        uses : echapmanFromBunnings/upload-artifact@3.0.0
        with :
          name : my first artifact
          path : .
