name : demo7
on : [push]

jobs :
   check : 
     runs-on : ubuntu-latest
     steps : 
     - name : check the code
       uses : actions/checkout@v2
     - run : python pythonapp.py
   build : 
     runs-on : ubunut-latest
     needs : [check]
     steps : 
     - uses : actions/checkout@v2
     - uses : actions/upload-artifact@v4
       with : 
         name : myartifact
         path : .
       
     
