name : demo5
on : [push]



jobs : 
   secretcheck :
      runs-on : windows-latest
      steps : 
      - name : secret check
        uses : aws-actions/configure-aws-credentials@v4
        with : 
             aws-access-key-id: ${{secrets.AMAZON_ID}}
          
      - run : echo "cannot be shown bcs it secret "
